### ISSUE TITLE
Can we make this repo cross-platform?

### ISSUE THREAD

**Issue by simbaforrest** [coperception/coperception#1]
Currently, it only supports Linux:

https://github.com/coperception/coperception/blob/9bbde1bc908f06905a82f42d044e9ccc95256512/coperception/utils/mapping.py#L4

**Comment by dekunma** [comment]
That's one of the issues I have in mind. Also currently we only support python 3.7,  
I'll definitely try to make the library compatible with more major OSs and python environments in some near-feature releases.

**Comment by dekunma** [comment]
Update: Windows system is now supported.

**Comment by simbaforrest** [comment]
Great. Thanks!
