### ISSUE TITLE
Could you provide the teacher checkpoint?

### ISSUE THREAD

**Issue by huiyegit** [coperception/coperception#10]
To train the Disco model, there is an argument, --resume_teacher. How to get this teacher model?  Could you provide the checkpoint or the way to train this model?
![Selection_030](https://user-images.githubusercontent.com/31486250/180662085-0162e95a-d0bf-4aeb-beb0-514464d482e6.png)

**Comment by huiyegit** [comment]
The upperbound model is the teacher model. Thanks.

**Comment by huiyegit** [comment]
Thanks.

**Comment by Maya-ank** [comment]
> The upperbound model is the teacher model. Thanks.

I was looking for it. Thanks
