### ISSUE TITLE
How to put all agents to the same map?

### ISSUE THREAD

**Issue by fandulu** [coperception/coperception#11]
Thanks very much for showing this great work to us.

May I ask a question? For the detection, each agent detects the boxes on their own ego map, how could I put detections of all agents on the same map? I tried to find the location parameters to connect the detection outputs, but I am sorry they are too complicated, and I cannot figure them out.

**Comment by simbaforrest** [comment]
Do you mean how to visualize/draw/plot all the agents and all the detections in a single view?

@dekunma I think we have a visualization module for this, right?

**Comment by dekunma** [comment]
@simbaforrest Yes, we have visualization located in [coperception/coperception/tools/visualization](https://github.com/coperception/coperception/tree/master/tools/visualization/v2xsim_vistool), but this module is used to visualize the original V2X-Sim dataset.
@fandulu If you are trying to put the detection boxes of all the agents on a single global map, unfortunately it is not supported by our SDK currently.
However, we implemented the functionality to fuse the detection boxes of every other agents to the ego map of one agent:
https://github.com/coperception/coperception/blob/59e8fa36a315bf652bf2eb9f0c64dc3cbca61d34/tools/det/test_codet.py#L312-L315
this process is called `late fusion` by us.
Hopefully this would be helpful to you.

**Comment by fandulu** [comment]
@dekunma and @simbaforrest, thanks very much for your kind replies! 
To @dekunma , may I understand that the variable [trans_matrices](https://github.com/coperception/coperception/blob/59e8fa36a315bf652bf2eb9f0c64dc3cbca61d34/tools/det/test_codet.py#L229) are used to describe the relationship between each ego view? And we can use them to transfer the detections across different views?

**Comment by dekunma** [comment]
@fandulu You are right. 
For example `trans_matrices[0, j, i]` is the transformation matrix to transfer the detections from agent `i` to agent `j`.
This way you can transfer detections across different views.

**Comment by fandulu** [comment]
Got it. Thanks again!
