### ISSUE TITLE
error in dataset preprocessing

### ISSUE THREAD

**Issue by zllxot** [coperception/coperception#12]
Hi, thanks for your excellent work!
When I run `make create_data` command, I got the following error: 

![image](https://user-images.githubusercontent.com/109151298/193716433-52534b72-a2d3-42b1-8e5a-fca56abed866.png)

Through debug, I traced back to _line 57_ in `coperception/utils/nuscenes_pc_util.py`, and found that the caculation result of `num_sensor` is 0, so the content inside the for loop will not be executed, which causes `trans_matrix_list` (_line 115_) to be empty.

![image](https://user-images.githubusercontent.com/109151298/193717347-bc0510d1-912a-4f90-93ff-1f6aece3594a.png)

![image](https://user-images.githubusercontent.com/109151298/193717823-8ab4c554-5d82-4104-a5cd-5dc5606c8155.png)

Could you tell me what the problem is?

**Comment by simbaforrest** [comment]
@dekunma @RoboticsYimingLi any comments?

**Comment by dekunma** [comment]
@zllxot Hi, based on your output, I'm guessing that the V2X-Sim 2.0 dataset you downloaded is not complete.
Here is the output from my end when I run the script:
![image](https://user-images.githubusercontent.com/53892579/193934367-14bb939b-d036-4598-a8cb-7dd731a75a2f.png)
you can tell that the numbers printed under `Loading NuScenes tables for version v1.0-mini...` is different from those on your end.
Could you please try to double-check if the dataset your downloaded is intact? You can also download the already parsed datasets [on our website](https://ai4ce.github.io/V2X-Sim/download.html) and use those directly for detection/segmentation/tracking tasks.
Feel free to follow up on this issue if the problem persists.

**Comment by zllxot** [comment]
> @zllxot Hi, based on your output, I'm guessing that the V2X-Sim 2.0 dataset you downloaded is not complete. Here is the output from my end when I run the script: ![image](https://user-images.githubusercontent.com/53892579/193934367-14bb939b-d036-4598-a8cb-7dd731a75a2f.png) you can tell that the numbers printed under `Loading NuScenes tables for version v1.0-mini...` is different from those on your end. Could you please try to double-check if the dataset your downloaded is intact? You can also download the already parsed datasets [on our website](https://ai4ce.github.io/V2X-Sim/download.html) and use those directly for detection/segmentation/tracking tasks. Feel free to follow up on this issue if the problem persists.

Thank you for your prompt reply!
In fact, I'm trying to train the DiscoNet model, which is based on the V2X-Sim 1.0 dataset. In this case, should I download the V2X-Sim 2.0 dataset?

**Comment by zllxot** [comment]
@dekunma By using the parsed V2X-Sim 2.0 dataset directly, I can already train the model normally. Thanks again.

**Comment by dekunma** [comment]
> @dekunma By using the parsed V2X-Sim 2.0 dataset directly, I can already train the model normally. Thanks again.

Sounds good! I'll close this issue for now. If you encounter other problems, feel free to reopen this issue or submit a new one.
