### ISSUE TITLE
LowerBound and UpperBound Test run issue

### ISSUE THREAD

**Issue by rajuptvs** [coperception/coperception#13]
First of all, I would like to thank you all and appreciate the work that has been put into this project. 

So, Regarding the issue, When trying to do the test for BEV Segmentation task using either the lower bound or the upper bound approach, Getting an issue with invalid key error for ['trans matrices'] 

![image](https://user-images.githubusercontent.com/48201939/193916784-fb1cb402-715a-45d1-9800-cf21a16f33ef.png)

Would greatly be helpful, if someone can assist me in knowing what the issue is actually. 

Thanking you in advance

**Comment by dekunma** [comment]
Hi @rajuptvs, thanks for pointing this out! This bug was introduced when I was refactoring the API earlier. I'll fix this in the following commit.

**Comment by rajuptvs** [comment]
Hey thanks, for the quick response. Just wanted to check regarding the dataset, Dataset has the images, but I don't see the images being utilized for any of the training models. Is that correct? 

Thanking you in advance

**Comment by dekunma** [comment]
> Hey thanks, for the quick response. Just wanted to check regarding the dataset, Dataset has the images, but I don't see the images being utilized for any of the training models. Is that correct?
> 
> Thanking you in advance

@rajuptvs Hi, are you referring to the images captured by the RGB cameras? If so, then yes, currently we are not using any of these images.
![image](https://user-images.githubusercontent.com/53892579/198063717-a9374498-2ab3-405f-99d5-1749e1629ff4.png)
