### ISSUE TITLE
Data augmentation methods used for training object detection models

### ISSUE THREAD

**Issue by quan-dao** [coperception/coperception#15]
Hello,
Thank you for making your dataset and SDK available.
I have one question about the training of object detection models. Do you use any data augmentation methods (e.g., world rotation, flipping, ground truth sampling) during the training of these models?

**Comment by dekunma** [comment]
Hi @quan-dao, 
No, we did not use any of these data augmentation methods. However, by setting the `--pose_noise` argument during training, pose noise will be added, which is also a type of augmentation.
