### ISSUE TITLE
Question about decoder

### ISSUE THREAD

**Issue by zllxot** [coperception/coperception#16]
Hi, I have a question about the decoder implementation details in [backbone](https://github.com/coperception/coperception/blob/dd8fbb660300ee763e0bac870f63fc4987440a35/coperception/models/det/backbone/Backbone.py). 
In my understanding, the encoder and decoder are usually deployed on different vehicles in the actual V2V scenario, which means that the decoder cannot obtain the information from the encoder.
However, in the decoder code, each layer of the decoder first concatenates the previous feature map with the corresponding feature map in the encoder, and then uses a 1 x 1 convolutional operation to halve the number of channels. Is this reasonable?

**Comment by RoboticsYimingLi** [comment]
Hi, thanks for the question. The decoder cannot obtain encoded messages from other vehicles, but it can use its own features. It only fuses the message from others at one layer, all other layers only use its own features.

**Comment by zllxot** [comment]
> Hi, thanks for the question. The decoder cannot obtain encoded messages from other vehicles, but it can use its own features. It only fuses the message from others at one layer, all other layers only use its own features.

Thanks for addressing my confusion!
