### ISSUE TITLE
error in V2X-Sim Tutorial

### ISSUE THREAD

**Issue by emoemo00** [coperception/coperception#18]
Hey, thank you for the great work. I am just following the tutorial to try the V2X-Sim 2.0 dataset. But I am facing an issue

> AssertionError: Error: there are 47638 label files but 47300 lidarseg records.

when running: `nusc = NuScenes(version='v1.0-mini', dataroot=in_path, verbose=True)`.

**Issue output:** 

> Loading NuScenes tables for version v1.0-mini...
> Loading nuScenes-lidarseg...

> AssertionError                            Traceback (most recent call last)
> /tmp/ipykernel_5481/2787126174.py in <module>
> ----> 2 nusc = NuScenes(version='v1.0-mini', dataroot=in_path, verbose=True)
> 
> ~/anaconda3/envs/nuscenes/lib/python3.7/site-packages/nuscenes/nuscenes.py in __init__(self, version, dataroot, verbose, map_resolution)
>     102             num_lidarseg_recs = len(getattr(self, lidar_task))
>     103             assert num_lidarseg_recs == num_label_files, \
> --> 104                 f'Error: there are {num_label_files} label files but {num_lidarseg_recs} {lidar_task} records.'
>     105             self.table_names.append(lidar_task)
>     106             # Sort the colormap to ensure that it is ordered according to the indices in self.category.
> 
> AssertionError: Error: there are 47638 label files but 47300 lidarseg records.

I think the issue is caused by the number of files in 'lidarseg' folder does not match with the number of lidarseg records in 'lidarseg.json'. Could you help me to figure this out? Thank you!

**Comment by zl3466** [comment]
> Hey, thank you for the great work. I am just following the tutorial to try the V2X-Sim 2.0 dataset. But I am facing an issue
> 
> > AssertionError: Error: there are 47638 label files but 47300 lidarseg records.
> 
> when running: `nusc = NuScenes(version='v1.0-mini', dataroot=in_path, verbose=True)`.
> 
> **Issue output:**
> 
> > Loading NuScenes tables for version v1.0-mini...
> > Loading nuScenes-lidarseg...
> 
> > AssertionError                            Traceback (most recent call last)
> > /tmp/ipykernel_5481/2787126174.py in 
> > ----> 2 nusc = NuScenes(version='v1.0-mini', dataroot=in_path, verbose=True)
> > ~/anaconda3/envs/nuscenes/lib/python3.7/site-packages/nuscenes/nuscenes.py in **init**(self, version, dataroot, verbose, map_resolution)
> > 102             num_lidarseg_recs = len(getattr(self, lidar_task))
> > 103             assert num_lidarseg_recs == num_label_files, 
> > --> 104                 f'Error: there are {num_label_files} label files but {num_lidarseg_recs} {lidar_task} records.'
> > 105             self.table_names.append(lidar_task)
> > 106             # Sort the colormap to ensure that it is ordered according to the indices in self.category.
> > AssertionError: Error: there are 47638 label files but 47300 lidarseg records.
> 
> I think the issue is caused by the number of files in 'lidarseg' folder does not match with the number of lidarseg records in 'lidarseg.json'. Could you help me to figure this out? Thank you!

Hey there, thank you for looking into our project.

You are absolutely correct that this error is caused by a mismatch between the amount of records in the .json file and the amount of actual data file. According to the NuScene devkit original codebase [here](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py), line 103-104, the "label file" represents the actual data file that ends in .bin or .npy, and record indicates the items listed in the .json file. This error message has pointed out that the mismatch occurred in the lidarseg folder.

For now I would recommend you to check the amount of files in your lidarseg folder and see if that counts to 47300 (since the record could make no mistake, and the fact that 47300 is devisable by 100 makes the count creditable). If the file count in the folder is not 47300, then scan through the files with attention on the indexes in the filenames to see for any abnormal items. The original V2X-Sim 2.0 dataset should be having the appropriate amount of files matching the .json records. 

Hope this helps.

**Comment by emoemo00** [comment]
> 
Hey, thank you for your prompt response.

I did a quick scan through the files inside the `lidarseg` folder. Here is the total number I got **47638**.
![error](https://user-images.githubusercontent.com/117551421/200154201-1521da38-955b-4568-b35b-637c3fb1a3c4.png)

Then, I checked the number of files for each scene. All the scenes contain the number of files which are devided by 100 (e.g., 400, 500, etc.), except scenes 74 and 75. Each of them contains 419 files and I am guessing here is the problem.

Since I did no modification on the dataset folders (just directly downloaded from https://drive.google.com/drive/folders/1nVmY7g_kprOX-I0Bqsiz6-zdJM-UXFXa), could you please check if the `lidarseg` folder in the google drive has the correct number of files?

Thank you!

**Comment by dekunma** [comment]
Hi @emoemo00,
Could you share with us which version of `nuscenes-devkit` you are using? On my end I'm using version `1.0.9` (as specified in https://github.com/coperception/coperception/blob/a7a8bc240f311449f852cd5810386c274e71a443/requirements.txt#L6), and I was unable to reproduce the error you encountered (I didn't even have the line of `Loading nuScenes-lidarseg...` in my output...).
Also, I believe we are not using the semantic LiDAR sensor (`lidarseg`) in this codebase. If you just want to run detection/segmentation/tracking tasks supported by this codebase, I would recommend using our [parsed V2X-Sim 2.0 dataset](https://drive.google.com/drive/folders/1zFK9VWvXvYUHatKod5PTl8kZxSFskGGE) which can be used directly for training and testing (without the step of creating data).

**Comment by emoemo00** [comment]
Hi @dekunma, thank you for the help.

The problem was fixed by using `nuscenes-devkit` version `1.0.9`.
