### ISSUE TITLE
Disco Test result query

### ISSUE THREAD

**Issue by Maya-ank** [coperception/coperception#33]
Thankyou for your support and kind respose in my issues. 
I have one small question related to my Test result of disco with rsu . 
In the average local mAP, I think there is some error as it is not actually the average of all the 5 agents. 
Can you please help me to understand this. 

![Disco_Test_result](https://user-images.githubusercontent.com/91845852/234569474-24eef0e8-9230-4c4e-8616-a6cd65b81c2a.PNG)

**Comment by dekunma** [comment]
Thank you for pointing this out. There was indeed an error in the evaluation code that results in incorrect logging of the individual agents, but the average local mAP (the last line) should be correct. I will fix this in the upcoming commit.

**Comment by Maya-ank** [comment]
@dekunma Thankyou for your response
