### ISSUE TITLE
Question about Downloading cam_int.zip

### ISSUE THREAD

**Issue by lianggroup** [coperception/coperception#34]
Hi. Last time I asked a question about downloading the full dataset due to some damaged .zip files which cannot be unzip. And thanks for your effort on uploading the whole dataset. I successfully downloaded and unzipped all .zip files but `cam_int.zip` (39GB). Can you solve this problem? Looking forward to your reply and appreciating all your effort.

**Comment by simbaforrest** [comment]
@dekunma can you check that file? Thank you.

**Comment by dekunma** [comment]
My guess is that `cam_int.zip` is too big to be downloaded easily. I will split it into two files, each of which will be around 20GB, and upload them today. 
If you are encountering some other problems besides this, please let me know @lianggroup.

**Comment by dekunma** [comment]
@lianggroup I have split `cam_int.zip` into `cam_int1.zip` and `cam_int2.zip` and uploaded them to both Baidu Netdisk and Google Drive. Please try if you are able to download them now.

**Comment by lianggroup** [comment]
I‘ve successfully downloaded and unzipped the `cam_int.zip`. Thanks a lot!
