### ISSUE TITLE
Plotting edge weights

### ISSUE THREAD

**Issue by darkdevahm** [coperception/coperception#37]
I was trying to plot the edge weights as indicated in the tools/det./test_codet.py, but when I uncomment the plots seemed to be empty. 
https://github.com/coperception/coperception/blob/7a3a543d94dd9f14c064dd46017cf51d0a342722/tools/det/test_codet.py#L348

**Comment by dekunma** [comment]
Thanks for pointing this out. This error will be fixed in the following commit. After setting the argument `visualization` to `1`, you will be able to plot the edge weights of DiscoNet.
