### ISSUE TITLE
Question about Tracking

### ISSUE THREAD

**Issue by fanyimeng0** [coperception/coperception#44]
Hi, thanks for your excellent work!
When I try to use tools of tracking with data V2X-SIM-v2.0-mini, I don't know where is the “det_data_path" (the path of the preprocessed detection dataset.) Could you give me some guidance?

**Comment by dekunma** [comment]
Hi @fanyimeng0 , please preprocess the V2X-Sim-2 mini detection dataset by running `make create_data` in `tools/det` on it. 
Then when running the tracking task, set `det_data_path` to the processed dataset (the dataset you created using the command above). 
This process is going to take a relatively short period of time, so I didn't upload the preprocessed mini dataset like what I did for the full dataset.

**Comment by fanyimeng0** [comment]
Thanks for your response!
