### ISSUE TITLE
DLL load failed: The specified module could not be found while runnig file examples in "coperception"

### ISSUE THREAD

**Issue by eyabesbes** [coperception/coperception#47]
Hello,
I have installed "coperception" on windows 10 using the following documentation:
![image](https://github.com/ms-van3t-devs/ms-van3t/assets/95165444/2b77c69c-e908-4134-b48e-ed8fbfe2f740)
However, I'm having this problem every time I try to execute one of the example files within the coperception folder:
![image](https://github.com/ms-van3t-devs/ms-van3t/assets/95165444/6f921c9e-f345-4b87-8d33-2e66fcd1184d)
To solve this issue, I have installed the Microsoft Visual C++ Redistributable latest supported downloads and It didn't work either. I have also tried to update pip and run this command on conda: ```pip install msvc-runtime ``` and the error is still persistent.

**Comment by dekunma** [comment]
`coperception/utils/mapping/mapping.cp37-win_amd64.pyd` is the DLL file I built on my Windows 11 machine. Looks like it does not work on Windows 10.
I would recommend using one of our supported systems: `Ubuntu 18.4; RHEL 8.4; Windows 11` to avoid this issue. (Ubuntu for the best, to avoid other potential issues).
Or, you can also try to build the dll from `coperception/utils/mapping/dynamic_library` if you are familiar with C++ building process on Windows. (Otherwise, the building process can be kind of painful. At least to me.)

**Comment by eyabesbes** [comment]
> `coperception/utils/mapping/mapping.cp37-win_amd64.pyd` is the DLL file I built on my Windows 11 machine. Looks like it does not work on Windows 10. I would recommend using one of our supported systems: `Ubuntu 18.4; RHEL 8.4; Windows 11` to avoid this issue. (Ubuntu for the best, to avoid other potential issues). Or, you can also try to build the dll from `coperception/utils/mapping/dynamic_library` if you are familiar with C++ building process on Windows. (Otherwise, the building process can be kind of painful. At least to me.)

Hi, thank you for your reply.
I've upgraded my OS to Windows 11, and I've deleted 'coperception' and reinstalled it, but I'm still encountering the same error. To be honest, I'm not familiar with the C++ building process on Windows. Do you have any ideas on how I can solve this issue?

**Comment by dekunma** [comment]
It looks like you are running the code from a Jupyter Notebook (based on the screenshot you provided). We haven't tested our code in Jupyter Notebook, and that might be the issue.
In general, I would recommend using a Linux machine (Or WSL. The code works on Ubuntu WSL on my Windows machine) if it still doesn't work outside of a Jupyter Notebook.
