### ISSUE TITLE
Support AttentiveFusion and V2X-ViT model

### ISSUE THREAD

**Issue by DerrickXuNu** [coperception/coperception#9]
Hi team,

Thanks for your great work! Do you have plan to support AttentiveFusion model in OPV2V (ICRA2022) and V2X-ViT (ECCV2022) in your framework? 

@RoboticsYimingLi @dekunma @simbaforrest

**Comment by simbaforrest** [comment]
Haha Runsheng @DerrickXuNu , yes of course. In fact, we hope you and others could join this open-source effort! Do you want to be added to the core management team?

@dekunma is currently working on improving the readme about how everyone could join this effort freely via Git and GitHub. Basically you can add V2X-ViT models (and your dataset's dataloaders!) to this repo by filling a pull request.

**Comment by DerrickXuNu** [comment]
Yeah, it would be great if I can be added to the core team!

Adding dataloader for opv2v/v2xset may take some time, but we could start from adding methods to this repo.

**Comment by DerrickXuNu** [comment]
Thanks for adding me to this. 
Yeah, I will invite my teammates as well! I agree that having a unified codebase would be great for the whole community. Letting the codebase support both datasets may take some time, but we can sync up the methods first to have the momentum. I will also adopt DiscoNet in OpenCOOD in the next few days, so people who want to try OPV2V in the near future can also compare it with DiscoNet. I will let Yiming be the reviewer for that.
